Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.68.1"
  config.vm.provision "shell", inline: <<-SHELL
    echo "Create container namespace"
    ip netns add container

    echo "Create a veth pair"
    ip link add veth-host type veth peer name veth-con

    echo "Create the bridge interface"
    ip link add name br0 type bridge
    ip addr add 10.0.0.1/24 dev br0
    ip link set br0 up

    echo "Connect host end to the bridge"
    ip link set veth-host master br0
    
    echo "Turn on host end"
    ip link set veth-host up

    echo "Connect container end to the namespace"
    ip link set veth-con netns container
    
    echo "Assign IP address to the container end"
    ip netns exec container ip addr add 10.0.0.11/24 dev veth-con

    echo "Turn on container end"
    ip netns exec container ip link set veth-con up

    echo "Turn on packet forwarding"
    sysctl -w net.ipv4.ip_forward=1
    
    echo "Add a default route to the bridge in the container namespace"
    ip netns exec container ip route add default via 10.0.0.1
  SHELL
end