apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    # Selects pods with `app: postgres` label
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      # Matches on pods with `app: postgres` label - similar to how Deployment matches on pods
      app: postgres
  serviceName: "postgres"
  # By default is 1
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        # Creates pods with `app: postgres` label
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_ROLE
          valueFrom:
            fieldRef:
              # Use pod name for role assignment - e.g. postgres-0, postgres-1
              fieldPath: metadata.name
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
# Here we have to ensure the volumes are replicated - something we do ourselves